version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: